### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by DanielHabenicht** [d4l-data4life/covapp#19]
Hi, I can provide the [crowdin.com](crowdin.com) platform for internationalization of the app. 

I already created an approved OpenSource Organization for the #WeVsVirus Hackathon here: https://wevsvirushack.crowdin.com/

I created a project for translation for you: 
https://wevsvirushack.crowdin.com/covapp
 
You can integrate it easily into your repo so updates are provided automatically, till then I can update it via a PR. Just contact me via email for integration: daniel-habenicht@outlook.de

**Comment by chris-aeviator** [comment]
@DanielHabenicht I'd be willing on working to implement i18n as soon as there are translations available

**Comment by DanielHabenicht** [comment]
What do you mean by that? 

There is already an internationalisation file here: https://github.com/d4l-data4life/covapp/tree/master/src/global/i18n

**Comment by chris-aeviator** [comment]
If thats the case and its setup my offer is obsolete, otherwise happy to contribute by setting up everything needed to have a language selection

Am 3. April 2020 13:41:01 GMT+07:00 schrieb DanielHabenicht <notifications@github.com>:

**Comment by meduzen** [comment]
I started a [French translation](https://gist.github.com/meduzen/a2a60f9ca461d47104e2c72f22deceef). Anyone can complete, awaiting me to continue.

@DanielHabenicht Would you accept a French translation, once done? (And maybe a revamp of the language selector.)

**Comment by DanielHabenicht** [comment]
I am not with the maintainer of this repo. 
But you can add your translations easily here: https://wevsvirushack.crowdin.com/covapp

**Comment by comradekingu** [comment]
L10n is good, Crowdin isn't.

Please don't use Crowdin, it is a lackluster tool in terms of ensuring quality, cumbersome to use, and is closed source software only-as-a-service that spies on users https://support.crowdin.com/cookies/.

I recommend using https://weblate.org/hosting/, which unlike Crowdin offers gratis hosting to all libre software projects, without requiring them to be non-commercial and contribute to their TM.

**Comment by radibit** [comment]
@DanielHabenicht 

As part of the latest [release 1.14.0](https://github.com/d4l-data4life/covapp/releases/tag/1.14.0), we've introduced a workflow that can be used by collaborators to include additional translations 🙂 Please be sure to check the updated [CUSTOMIZATION.md](https://github.com/d4l-data4life/covapp/blob/master/docs/CUSTOMIZATION.md#using-the-example-languages-and-contributing-a-new-language) document on how to add the translations you and the people that worked on them via the Crowdin service.

Feel free to close the current issue if they aren't any additional questions.

**Comment by DanielHabenicht** [comment]
@radibit If you want, you can add the Crowdin GitHub Extension that can automatically create a PR if a new language gets translated. This would open the translation workflow to non-programmers ;)

Just mail me (daniel-habenicht@aquiver.de) so I can give you access to Crowdin project. 
For an example look at this PR: https://github.com/CovOpen/CovQuestions/pull/48

**Comment by comradekingu** [comment]
@DanielHabenicht Why would anyone want to use Crowdin, or subject users to that level of tracking and profiling?

**Comment by radibit** [comment]
I'm closing this issue since there isn't any interest of integrating a service like Crowding and because there is already an option for contributors to add various translations by opening a pull request to this repository directly following the [customization documents](https://github.com/d4l-data4life/covapp/blob/master/docs/CUSTOMIZATION.md).
