### ISSUE TITLE
Bug fix for issue with app.css in stencil.config.ts, color customization not working!

### ISSUE THREAD

**Issue by BucketHaendl** [d4l-data4life/covapp#36]
**There's a bug in the stencil.config.ts file which prevents any color customization!**

The following code at line 14 f.:

`  globalStyle:
    process.env.LAYOUT === 'OFFICIAL_COLLABORATION_BZGA'
      ? 'src/global/app-collaboration-bzga.css'
      : 'src/global/app.css',`

should be replaced by:

`  globalStyle: 'src/custom/styles/app.css',`

Took me a day to finally track down the problem and find the solution.
Hope this is helpful for others who run into the same issue! :)

**Comment by radibit** [comment]
@BucketHaendl Thank you so much for bringing that to our attention and I'm really sorry for the confusion that this bug led to and the time you spent figuring out its source 😞

It'll be fixed right away with the next release, planned for later today.

**Comment by radibit** [comment]
@BucketHaendl the requested fix has been already released as part of [1.14.0](https://github.com/d4l-data4life/covapp/releases/tag/1.14.0). Thanks once again!
