### ISSUE TITLE
Fallback language failed

### ISSUE THREAD

**Issue by Osch-info** [d4l-data4life/covapp#42]
If 'en' is not part of the SUPPORTED_LANGUAGES-Const in .env, the fallback language breaks the app if the the default language of the browser is 'en'.

**Comment by chaeringer** [comment]
Hello @Osch-info, thanks for your feedback!

Please note that the default fallback language is English (en) and it has to be available.
This remark is now also part of the documentation:
https://github.com/d4l-data4life/covapp#customization

If it is not an option for you to provide englisch translation files, you could configure the app 
to use eg. DE as a fallback:
https://github.com/d4l-data4life/covapp/blob/master/src/global/utils/i18n.ts#L40

⚠️ Please take into consideration that this change is not something that is part of our customization flow and a new release of the covapp could potentially break or revert your change.
