### ISSUE TITLE
Errors in fhir/respons.ts

### ISSUE THREAD

**Issue by mulver64** [d4l-data4life/covapp#55]
See the png for the errors while compiling
![2020-06-08 17_09_57-Stencil_ App](https://user-images.githubusercontent.com/66622016/84047034-20063180-a9ab-11ea-8cd3-b5c5872941b4.png)

**Comment by SanderMuller** [comment]
I experience the same issue. Pulling in tag `1.18.0` and `npm start` runs fine, but with the latest tag (`1.19.0`) I get the same errors as in this issue.
