### ISSUE TITLE
Incorrect date format on US iPhone when setting the app language to German

### ISSUE THREAD

**Issue by stephanadler1** [d4l-data4life/covapp#83]
To reproduce this issue:

1. Use an iPhone configured for the US market. Could potentially be reproduced on a German iPhone configured for US language settings too.
2. Install the CovPass app from the US app store
2. In the Settings app, configure the CovPass app to use "German" as the preferred language

![CovPass-SettingsGerman](https://user-images.githubusercontent.com/11354772/146745290-0babf5cc-18b2-422a-a1ef-7e1928a3507c.png)

3. Open the CovPass app. Notice that the date of the certificate is shown in **Month/Day/Year** format (the default for US english) instead of the expected **Day.Month.Year** format.
![CovPass-WrongDateFormat](https://user-images.githubusercontent.com/11354772/146745294-2a71233f-39ec-430f-8fb4-da6faf7593bb.png)

**Comment by chaeringer** [comment]
Hello @stephanadler1, thanks for opening this issue. Unfortunately this is **not** the repository for the CovPass app.
This repository was used for the code of https://covapp.de/
